# Generated by Django 2.0.7 on 2018-07-16 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0002_auto_20180713_1918'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=30)),
            ],
        ),
    ]
