# Generated by Django 2.0.7 on 2018-07-16 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0004_jeu_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='jeu',
            name='censure',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='jeu',
            name='datesortie',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='jeu',
            name='developpeur',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='jeu',
            name='editeur',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='jeu',
            name='nomVO',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='jeu',
            name='genre',
            field=models.ManyToManyField(null=True, to='guide.Genre'),
        ),
    ]
