# Generated by Django 2.0.7 on 2018-07-17 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0006_auto_20180716_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jeu',
            name='censure',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jeu',
            name='datesortie',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jeu',
            name='developpeur',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='jeu',
            name='editeur',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='jeu',
            name='nomVO',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
