# Generated by Django 2.0.7 on 2018-07-17 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0007_auto_20180717_0025'),
    ]

    operations = [
        migrations.AddField(
            model_name='jeu',
            name='multi',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jeu',
            name='solo',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
