# Generated by Django 2.1 on 2018-09-04 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0008_auto_20180717_0103'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jeu',
            options={'verbose_name': 'jeu', 'verbose_name_plural': 'jeux'},
        ),
        migrations.AlterField(
            model_name='jeu',
            name='datesortie',
            field=models.DateField(blank=True, null=True, verbose_name='date de sortie'),
        ),
        migrations.AlterField(
            model_name='jeu',
            name='genre',
            field=models.ManyToManyField(blank=True, to='guide.Genre'),
        ),
    ]
