# Generated by Django 2.1 on 2018-09-05 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0010_jeu_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jeu',
            name='multi',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='jeu',
            name='solo',
            field=models.BooleanField(default=False),
        ),
    ]
