# Generated by Django 2.1.1 on 2018-09-08 15:33

from django.db import migrations
import guide.models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0011_auto_20180905_1350'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jeu',
            old_name='test',
            new_name='Autres',
        ),
        migrations.AddField(
            model_name='jeu',
            name='MissionsAnnexes',
            field=guide.models.ListField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jeu',
            name='MissionsPrincipales',
            field=guide.models.ListField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jeu',
            name='Trophees',
            field=guide.models.ListField(default=1),
            preserve_default=False,
        ),
    ]
